### ISSUE TITLE
Refactor launch package

### ISSUE THREAD

**Issue by c71n93** [objectionary/ddr#108]
Before adding some functionality to aoi (https://github.com/objectionary/aoi/issues/39, https://github.com/objectionary/aoi/issues/40, https://github.com/objectionary/aoi/issues/41) most of the code needs to be refactored here. First of all `launch` package need to be refactored. 

Here:
https://github.com/objectionary/ddr/blob/7a013e8b893182b492ac33176291108c6eaad7db/src/main/kotlin/org/objectionary/ddr/launch/Combiner.kt#L43-L45
global variables are defined. `documents` variable is modified in functions `launch` and `buildGraph`. Then `documents` is used throughout the program, and also in [aoi](https://github.com/objectionary/aoi). 

The functions themselves here also do too much, so decomposition is broken. I think this code should be made more object-oriented. @yegor256, @mximp, WDYT?

**Comment by mximp** [comment]
@c71n93 I agree. Go ahead.

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#111](https://github.com/objectionary/ddr/issues/111) is still not solved.

**Comment by 0pdd** [comment]
@c71n93 the puzzle [#113](https://github.com/objectionary/ddr/issues/113) is still not solved; solved: [#111](https://github.com/objectionary/ddr/issues/111).

**Comment by 0pdd** [comment]
@c71n93 all 2 puzzles are solved here: [#111](https://github.com/objectionary/ddr/issues/111), [#113](https://github.com/objectionary/ddr/issues/113).
