### ISSUE TITLE
Release version 0.0.91

### ISSUE THREAD

**Issue by c71n93** [objectionary/ddr#115]
The `launch` package was completely refactored. Now this changes are necessary to refactor [aoi](https://github.com/objectionary/aoi) and [aoi2](https://github.com/objectionary/aoi2). 

@yegor256, could you release this changes, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.10`

**Comment by yegor256** [comment]
@c71n93 done

**Comment by c71n93** [comment]
@yegor256 thank you!

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#134](https://github.com/objectionary/ddr/issues/134), [#135](https://github.com/objectionary/ddr/issues/135) are still not solved.
