### ISSUE TITLE
Refactor GraphBuilder class

### ISSUE THREAD

**Issue by c71n93** [objectionary/ddr#119]
Issue https://github.com/objectionary/ddr/issues/116 depends on [`GraphBuilder`](https://github.com/objectionary/ddr/blob/d9d6fcf1b195ef09b8e29add530c0ff35639f693/src/main/kotlin/org/objectionary/ddr/graph/GraphBuilder.kt#L38) class. This class not suitable for changes now: lack of documentation and non-scalable code style. So, first of all, it is necessary to refactor `GraphBuilder`.

**Comment by 0pdd** [comment]
@c71n93 2 puzzles [#129](https://github.com/objectionary/ddr/issues/129), [#130](https://github.com/objectionary/ddr/issues/130) are still not solved.

**Comment by 0pdd** [comment]
@c71n93 all 2 puzzles are solved here: [#129](https://github.com/objectionary/ddr/issues/129), [#130](https://github.com/objectionary/ddr/issues/130).
