### ISSUE TITLE
Resolve unnecessary parameter `gather`

### ISSUE THREAD

**Issue by c71n93** [objectionary/ddr#121]
https://github.com/objectionary/ddr/blob/52c6bafb4b8fccbcf0fba98c552c1980ec42362c/src/main/kotlin/org/objectionary/ddr/sources/Sources.kt#L34

P.S. Due to an error in todo (forgotten `@`), `pdd` cannot recognize it.

**Comment by 0pdd** [comment]
@c71n93 5 puzzles [#123](https://github.com/objectionary/ddr/issues/123), [#124](https://github.com/objectionary/ddr/issues/124), [#125](https://github.com/objectionary/ddr/issues/125), [#126](https://github.com/objectionary/ddr/issues/126), [#127](https://github.com/objectionary/ddr/issues/127) are still not solved.

**Comment by 0pdd** [comment]
@c71n93 all 5 puzzles are solved here: [#123](https://github.com/objectionary/ddr/issues/123), [#124](https://github.com/objectionary/ddr/issues/124), [#125](https://github.com/objectionary/ddr/issues/125), [#126](https://github.com/objectionary/ddr/issues/126), [#127](https://github.com/objectionary/ddr/issues/127).
