### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/ddr#3]
Right now if you look at the `pom.xml` file you'll see commented out code for `.jar` creation.
If you uncomment it - you'll see that build fails with "Java heap space" error. 
I tried setting heap space like this, didn't help
```
<configuration>
  <argLine>-Xmx1024m</argLine>
</configuration>
```
We need to be able to create jar with dependencies to launch the app from console.

**Comment by yegor256** [comment]
@OlesiaSub I think you should try to use maven-assembly-plugin of version 3.4.2. The one you are using (2.6) is very old.

**Comment by OlesiaSub** [comment]
@yegor256 thanks a lot!
