### ISSUE TITLE
pom.xml is missing vital information for Maven Central release

### ISSUE THREAD

**Issue by yegor256** [objectionary/ddr#5]
See the information in https://github.com/objectionary/eo-files/blob/master/pom.xml#L37-L83 Without these details Maven Central won't accept our artifact

**Comment by OlesiaSub** [comment]
@rultor release, tag=`0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 can you please help?
Release fails due to this mistake:
```
[ERROR] Repository "orgeolang-1200" failures
[ERROR]   Rule "javadoc-staging" failures
[ERROR]     * Missing: no javadoc jar found in folder '/org/eolang/ddr/0.0.1'
```
But as stated in The Central Repository Documentation "Projects with packaging other than pom have to supply JAR files that contain Javadoc and sources.". I use pom.xml, so I don't understand why it requires a javadoc from me.

**Comment by yegor256** [comment]
@OlesiaSub Maven JavaDoc plugin doesn't find any files in `src/main/java` and doesn't build `-javadoc.jar` file for you project. Check this out: https://discuss.kotlinlang.org/t/generating-javadocs-kdocs-with-maven/839 A bad solution would be to put a single fake `.java` file into `src/main/java` just to trigger javadoc building. A good solution would be to learn how to use KDoc in Maven.

**Comment by OlesiaSub** [comment]
@yegor256 done, thanks!
